### PR TITLE
forms/formsets: Improve types

### PR DESCRIPTION
**Pull request by noelleleigh**
- Adds more specific types to all code in `django-stubs/forms/formsets.pyi`.
- Removes unnecessary assignments from module and class properties.
- `BaseFormSet` is now a generic class which contains a form type.

### CODE REVIEW

**Review by sbdchd — APPROVED** [review]
Thanks!

**Comment by collinanderson** [comment]
- `formset_factory` should accept `type[BaseForm]` not `BaseForm`.
- `BaseFormSet`'s `data` should also accept a `Mapping[str, Any]` like `BaseForm`, so it works with `request.POST`.
- `BaseFormSet`'s `initial` should take in a `list` of `dict`s, not a plain `dict` like `BaseForm`

**Comment by noelleleigh** [comment]
> * `formset_factory` should accept `type[BaseForm]` not `BaseForm`.
> * `BaseFormSet`'s `data` should also accept a `Mapping[str, Any]` like `BaseForm`, so it works with `request.POST`.
> * `BaseFormSet`'s `initial` should take in a `list` of `dict`s, not a plain `dict` like `BaseForm`

Feel free to make a PR for these.

**Comment by collinanderson** [comment]
ok PR here https://github.com/sbdchd/django-types/pull/288

**Pull request merged**
