### PR TITLE
Consider choices as literal and a lot more typing improvements

### LINKED ISSUE #34: Allow CharField to define a generic enum type
It would be nice to have support for this: https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types

Maybe something like this:

```python
class SomeEnum(models.TextFields):
    FOO = "foo"
    BAR = "bar"

some_enum_field = models.CharField[SomeEnum](  # note the [SomeEnum] generic here
    choices=SomeEnum.choices,
    default=SomeEnum.FOO,
)
```

This way the typing would know that the field reads and writes that exact enum type and not a str.

### LINKED ISSUE #51: Why is ManyToManyField not generic?
Is there a reason for the ManyToManyField not be able to be defined as this?

```
class ManyToManyField(Generic[_M], RelatedField[Sequence[_M], RelatedManager[_M]]):
```

### LINKED ISSUE #53: Why a `*` in `TextField.__init__` params ?
https://github.com/sbdchd/django-types/blob/7f8ed6ae7055a5496cd07e91217e536ddd290b75/typings/django/db/models/fields/__init__.pyi#L835-L840
https://github.com/sbdchd/django-types/blob/7f8ed6ae7055a5496cd07e91217e536ddd290b75/typings/django/db/models/fields/__init__.pyi#L862-L866

This `*` leads to.
```py
TextField('verbose name') # No overload variant of "TextField" matches argument types "str"
```

There is no `*` in the upstream, why is it added here?
https://github.com/typeddjango/django-stubs/blob/fb125609818057dff8aad807637b3ca9cca5e194/django-stubs/db/models/fields/__init__.pyi#L329

### PR DESCRIPTION
**Pull request by bellini666**
Ok, this started with me trying to make choices be automatically considered for typing validation. E.g.:

```python
class Foo(models.Model):
    c = models.CharField(choices=[("a": "A"), ("b": "B")])

f = Foo()
reveal_type(c)  # would display Literal["a", "b"]
f.c = "c"  # error
```

It worked very fine! I just had to implement __new__ for both `IntegerField` and `CharField` to make it work.

Then, since with the lack of `__init__` I wasn't getting arguments completion anymore, I implemented it generically on `Field`. I had to manually defined those on related fields and also on `ArrayField`, which I ended up improving their typing.

If you like this approach, it will be nice to do the same for all other fields (I can do that, just didn't because wasn't sure you were gonna like it).

Also, I tried a lot to avoid having to overload __new__ 4 times in each field but coudn't find a way :(. Maybe I'm missing something after looking to the same code for hours...

Fix #53 
Fix #51 
Fix #34

### CODE REVIEW

**Comment by bellini666** [comment]
Hey @sbdchd , did you have the opportunity to look at this? I know it is a very large PR with a lot of implications, but feel free to tell me if you need some better explanation or even something changed

**Comment by sbdchd** [comment]
Sorry for the delay!

I think right now it's tricky to review since it's so large, probably easier if its done in chunks

Also I want to support both mypy and pyright with this project. I tend to use pyright for intellisense and then mypy for actual type checking

**Comment by bellini666** [comment]
Hey @sbdchd , well, I can try to split this a bit if it helps. As I mentioned in [this comment](https://github.com/sbdchd/django-types/pull/55#issuecomment-950342028) 90% of the changes are actually pretty similar, it is just that there are lots of overloads that had to be added to all Field subclasses. There are some improvements to some typings, like the ManyToMany and ArrayField being able to resolve their types and also JSONField being able to receive a type to properly describe it.

Regarding mypy, it is actually working and the types are correct for it. The only strange thing is [this](https://github.com/sbdchd/django-types/pull/55/files#diff-dec76a00508873113e49ee05d1937ce5e24a7e05fdb3b1cc228d4ae82436561eL534). I really think that is a bug in mypy specifically with that `unreachable` code. I say that because, when I ask it to `reveal_type`, it says that it is indeed that type, it is not confused regarding it. Both it and pyright are reporting them being the same and also correctly.

**Comment by bellini666** [comment]
Hey @sbdchd ,

I just separated this PR into 5:

1) https://github.com/sbdchd/django-types/pull/62 : This is the first one that can be merged. I updated black/flake8 and installed flake8-pyi and fixed all related issues. All the bellow depends on this one

2) https://github.com/sbdchd/django-types/pull/63 : This improves RelatedFields and ManyToMany to properly type it.

3) https://github.com/sbdchd/django-types/pull/64 : This improves JSONField and allows us to type it and it will get validated. This can be useful to pass a TypedDict for example to define the JSONField schema.

4) https://github.com/sbdchd/django-types/pull/65 : This is the main change of this issue. It improves typing for _all_ fields in `fields/__init__.pyi`. Note that it depends on the others being merged first

5) https://github.com/sbdchd/django-types/pull/66 : This improves typing for arrayfields. Note that it depends on 4) being merged.

It should be safe to close this PR as the changes are separated into each one

**Comment by bellini666** [comment]
I'm closing this as it was splitted into many other PRs.

**Pull request closed without merging**
