### PR TITLE
fix: fix objects attribute for pyright 1.1.324

### PR DESCRIPTION
**Pull request by bellini666**
The way CPython works at runtime is to give a higher priority to the metaclass descriptors than the ones in the class itself.

Pyright 1.1.324 adjusted that but made our `.objects` typing break when using our own custom managers.

Nowadays we can use `Self` for that, which not only is more elegant but also solves this issue in a way that both mypy and pyright can resolve correctly.

Related issues:
- https://github.com/microsoft/pyright/issues/5792
- https://github.com/microsoft/pyright/issues/5686

### CODE REVIEW

**Review by sbdchd — APPROVED** [review]

**Comment by sbdchd** [comment]
This is great, thank you!!

**Comment by bellini666** [comment]
Thank you @sbdchd ! :)

Just to let you know, this solution has a [small issue](https://github.com/microsoft/pyright/issues/5803) on pyright 1.1.324 which will get resolved on 1.1.325. As soon as that version is released (probably in the next few days, based on pyright's release cadence) django-types can release a new version as well.

**Comment by last-partizan** [comment]
@bellini666 how about custom managers in app code?

Now we should use `objects: MyCustomManager = MyCustomManager()` for correct typing?

**Comment by bellini666** [comment]
> @bellini666 how about custom managers in app code?
> 
> Now we should use `objects: MyCustomManager = MyCustomManager()` for correct typing?

If you have a custom manager, indeed! That's what I do

**Comment by JakobGM** [comment]
> > @bellini666 how about custom managers in app code?
> > Now we should use `objects: MyCustomManager = MyCustomManager()` for correct typing?
> 
> If you have a custom manager, indeed! That's what I do

I think, and correct me if I'm wrong, an even more correct type annotation would be `objects: ClassVar[MyCustomManager]: MyCustomManager()`.

**Pull request merged**
