### PR TITLE
Array field

### PR DESCRIPTION
**Pull request by bellini666**
This was built on top of #65, so merging it should only keep this PR's change. Also, it has some dependencies for it to pass the tests that also apply to this one

### CODE REVIEW

**Comment by bellini666** [comment]
Just rebased this on top of https://github.com/sbdchd/django-types/pull/65 . Just like it, it needs other PRs to be merged before it so tests can pass

**Comment by bellini666** [comment]
Hey @sbdchd , just a heads up that this can now be reviewed/merged since https://github.com/sbdchd/django-types/pull/65 just got merged

**Comment by bellini666** [comment]
Hey @sbdchd , is there anything missing from this?

Also, are you planning to make a new release with the latest features that got merged soon?

**Comment by bellini666** [comment]
@sbdchd I rebased this on top of https://github.com/sbdchd/django-types/pull/97

**Comment by bellini666** [comment]
Hey @sbdchd , anything missing for this PR?

**Review by sbdchd — APPROVED** [review]

**Comment by sbdchd** [comment]
Thank you again!

**Pull request merged**
