### PR TITLE
Fix linting and testing errors

### PR DESCRIPTION
**Pull request by noelleleigh**
- Fixes Black formatting and import order in `django-stubs/db/transaction.pyi`.
- ~~Fixes expected Pyright error messages in `tests/pyright/test_arrays.py` and `tests/pyright/test_fields.py`.~~ Edit: With Python pinned to 3.8.18, these message changes are no longer necessary.

These changes allow `./s/lint` to run successfully on my machine.

### CODE REVIEW

**Review by sbdchd — APPROVED** [review]
Thanks!

**Review by sbdchd — APPROVED** [review]
Thanks!

**Comment by noelleleigh** [comment]
[Not sure what went wrong with Kodiak here](https://github.com/sbdchd/django-types/pull/272/checks?check_run_id=32166108457):

> ## ⚠️ problem contacting GitHub API with method 'kodiak/merged_blocked_unknown_reason'
> 
> Errors encountered when contacting GitHub API.
> 
>    - API call 'kodiak/merged_blocked_unknown_reason' failed with HTTP status '0' and response: "b''"
>    - API call 'kodiak/merged_blocked_unknown_reason' failed with HTTP status '0' and response: "b''"
>    - API call 'kodiak/merged_blocked_unknown_reason' failed with HTTP status '0' and response: "b''"
>   - API call 'kodiak/merged_blocked_unknown_reason' failed with HTTP status '0' and response: "b''"
>   - API call 'kodiak/merged_blocked_unknown_reason' failed with HTTP status '0' and response: "b''"

**Comment by noelleleigh** [comment]
@sbdchd What should be done about these Kodiak errors?

**Comment by sbdchd** [comment]
ah changing workflow files breaks the perms, I'll manually merge

**Comment by sbdchd** [comment]
Thank you!

**Pull request merged**
