### PR TITLE
feat: support for Django 4.2

### PR DESCRIPTION
**Pull request by bellini666**
* Add support for the new APIs in Django 4.2 that just got released
* Update mypy and pyright to their latest versions and fix all typing issues

### CODE REVIEW

**Comment by bellini666** [comment]
@sbdchd any idea why the tests failed to install the dependencies? The lockfile is updated correctly

**Comment by bellini666** [comment]
@sbdchd 

> re: the lock file, do you know what poetry version you're running? I'm guessing this repo has a really outdated version vs the one you're running:

I'm using the latest poetry version and my pip is also in the latest version.

I tried updating poetry and keep it uncapped (newer versions should be compatible with older lockfiles, so it is better to keep uncapped IMO, but I can cap it if you prefer). I also changed to python 3.8 instead of 3.7 (3.7 will EOL in a couple of months)

Still it seems that circleci is not using those versions. In [this run](https://app.circleci.com/pipelines/github/sbdchd/django-types/324/workflows/2a7bcaf0-fbbd-4f3f-bca4-a5891261cc63/jobs/324) I can see that it reported that poetry version was still an older one and also gave the same `WARNING: You are using pip version 21.2.4; however, version 23.0.1 is available.` just after it upgraded pip.

I don't know much of circleci (I usually run tests on github workflows). Am I missing something here?

**Comment by sbdchd** [comment]
I've replaced Circle with GitHub Actions, hopefully that avoids the poetry version nonsense

**Comment by bellini666** [comment]
> I've replaced Circle with GitHub Actions, hopefully that avoids the poetry version nonsense

Oh, that's awesome! Ok, updating my PR here

**Comment by sbdchd** [comment]
hmm not sure why GitHub Actions aren't running 🤔 

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by bellini666** [comment]
> hmm not sure why GitHub Actions aren't running thinking
> 
> https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

Maybe change to:

```yaml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
```

push I think only runs when you push to a branch in the repository itself, and the PR code is in the fork's repository

**Comment by bellini666** [comment]
@sbdchd I changed it in this PR and it is running now

**Comment by bellini666** [comment]
@sbdchd btw, I took the liberty of adjusting the tests file and modernize it with the current recommended way of installing dependencies managed by poetry. It seems that the tests worked fine now :)

Btw, what do you think about setting an auto release for PR merge events?
There are a lot of actions that can do that automatically, and it can use the PRs title if done using conventional commits (e.g. this is a `feat`) to increase the major/minor/patch versions automatically

**Comment by sbdchd** [comment]
Yeah auto release for merge makes a ton of sense!

**Review by sbdchd — APPROVED** [review]

**Pull request merged**
