### PR TITLE
Add PositiveBigIntegerField

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by sbdchd** [comment]
LGTM, thanks!

**Comment by benesch** [comment]
Woohoo, thanks very much! By the way, owe you big time for these stubs. 🙌🏽

**Comment by sbdchd** [comment]
Should be included in version 0.6.1

**Comment by benesch** [comment]
Indeed it is. Thanks for the quick release. I have a few more type errors
in my project so I’ll probably be sending a few more things your way.

**Pull request merged**
