### PR TITLE
Add missing admin filter and fix model indexes

### PR DESCRIPTION
**Pull request by duilio**
Hello, 

this PR actually makes two changes:

- add the missing `EmptyFieldListFilter`.
- fix the model `Index` class which also accepts positional parameters.

I am not sure if this is the right way to contribute to this repository.

- Is it ok to submit both changes in a single PR?
- How can I be sure everything is working fine? (a.k.a. tests)

### CODE REVIEW

**Comment by sbdchd** [comment]
ugh circle CI is broken

in terms of tests there are some in https://github.com/sbdchd/django-types/blob/72b6ec53b507ebf2a5290829c11c934d432104ec/tests/trout/models.py#L356-L364 where we essentially write some functions that expect a given type and type error if they get something else

**Comment by duilio** [comment]
@sbdchd in the meantime I've added some tests.
I had to push some other changes due to black formatting.

**Comment by sbdchd** [comment]
Okay I did what circleci said to do, logout and in again so maybe that's fixed it

can you push another commit?

it can be empty I think

```
git commit -m "fix ci" --allow-empty
```

**Comment by duilio** [comment]
@sbdchd unfortunately it doesn't seem to work yet.. :-( same message about oauth.

**Pull request merged**
